var status = 0;
var z = '#fUI/UIWindow/Quest/icon5/1#';
function start() {
    status = -1;
    action(1, 0, 0);
}
function action(p, f, u) {
    if (status == 0 && p == 0) {
        cm.dispose();
        return;
    }
    if (p == 1) {
        status++;
    } else {
        status--;
    }
    if (status == 0) {
        var o = '请选择你需要的物品\r\n';
        o += '#r#L0##v1102481# #z1102481##l\r\n';
        o += '#r#L1##v1102482# #z1102482##l\r\n';
        o += '#r#L2##v1102483# #z1102483##l\r\n';
        o += '#r#L3##v1102484# #z1102484##l\r\n';
        o += '#r#L4##v1102485# #z1102485##l\r\n';
        o += '#r#L5##v1072743# #z1072743##l\r\n';
        o += '#r#L6##v1072744# #z1072744##l\r\n';
        o += '#r#L7##v1072745# #z1072745##l\r\n';
        o += '#r#L8##v1072746# #z1072746##l\r\n';
        o += '#r#L9##v1072747# #z1072747##l\r\n';
        o += '#r#L10##v1082543# #z1082543##l\r\n';
        o += '#r#L11##v1082544# #z1082544##l\r\n';
        o += '#r#L12##v1082545# #z1082545##l\r\n';
        o += '#r#L13##v1082546# #z1082546##l\r\n';
        o += '#r#L14##v1082547# #z1082547##l\r\n';
        o += '#r#L15##v1132174# #z1132174##l\r\n';
        o += '#r#L16##v1132175# #z1132175##l\r\n';
        o += '#r#L17##v1132176# #z1132176##l\r\n';
        o += '#r#L18##v1132177# #z1132177##l\r\n';
        o += '#r#L19##v1132178# #z1132178##l\r\n';
        cm.askMenu(o);
    } else {
        if (status == 1) {
            switch (u) {
            case 0:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1102481)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 150);
                i.setMdd(r + 150);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君西亚戴斯披风一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君西亚戴斯披风#k1个');
                cm.dispose();
                break;
            case 1:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1102482)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 150);
                i.setMdd(r + 150);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君赫尔梅斯披风一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君赫尔梅斯披风#k1个');
                cm.dispose();
                break;
            case 2:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1102483)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 150);
                i.setMdd(r + 150);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君凯伦披风一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君凯伦披风#k1个');
                cm.dispose();
                break;
            case 3:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1102484)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 150);
                i.setMdd(r + 150);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君利卡昂披风一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君利卡昂披风#k1个');
                cm.dispose();
                break;
            case 4:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1102485)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 150);
                i.setMdd(r + 150);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君阿尔泰披风一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君阿尔泰披风#k1个');
                cm.dispose();
                break;
            case 5:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1072743)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 130);
                i.setMdd(r + 130);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君西亚戴斯靴一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君西亚戴斯靴#k1个');
                cm.dispose();
                break;
            case 6:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1072744)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 130);
                i.setMdd(r + 130);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君赫尔梅斯靴一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君赫尔梅斯靴#k1个');
                cm.dispose();
                break;
            case 7:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1072745)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 130);
                i.setMdd(r + 130);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君凯伦靴一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君凯伦靴#k1个');
                cm.dispose();
                break;
            case 8:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1072746)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 130);
                i.setMdd(r + 130);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君利卡昂靴一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君利卡昂靴#k1个');
                cm.dispose();
                break;
            case 9:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1072747)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 30);
                i.setMad(q + 30);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 130);
                i.setMdd(r + 130);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君阿尔泰靴一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君阿尔泰靴#k1个');
                cm.dispose();
                break;
            case 10:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1082543)).copy();
                i.setStr(t + 12);
                i.setDex(j + 12);
                i.setInt(g);
                i.setLuk(n);
                i.setPad(e);
                i.setMad(q + 15);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l + 300);
                i.setMaxMp(b);
                i.setPdd(h + 160);
                i.setMdd(r);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君西亚戴斯手套一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君西亚戴斯手套#k1个');
                cm.dispose();
                break;
            case 11:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1082544)).copy();
                i.setStr(t);
                i.setDex(j);
                i.setInt(g + 12);
                i.setLuk(n + 12);
                i.setPad(e + 15);
                i.setMad(q);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b + 300);
                i.setPdd(h);
                i.setMdd(r + 160);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君赫尔梅斯手套一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君赫尔梅斯手套#k1个');
                cm.dispose();
                break;
            case 12:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1082545)).copy();
                i.setStr(t + 12);
                i.setDex(j + 12);
                i.setInt(g);
                i.setLuk(n);
                i.setPad(e);
                i.setMad(q + 15);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l + 300);
                i.setMaxMp(b);
                i.setPdd(h + 80);
                i.setMdd(r + 80);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君凯伦手套一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君凯伦手套#k1个');
                cm.dispose();
                break;
            case 13:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1082546)).copy();
                i.setStr(t);
                i.setDex(j + 12);
                i.setInt(g);
                i.setLuk(n + 12);
                i.setPad(e);
                i.setMad(q + 15);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l + 300);
                i.setMaxMp(b);
                i.setPdd(h + 60);
                i.setMdd(r + 100);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君利卡昂手套一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君利卡昂手套#k1个');
                cm.dispose();
                break;
            case 14:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1082547)).copy();
                i.setStr(t + 12);
                i.setDex(j + 12);
                i.setInt(g);
                i.setLuk(n);
                i.setPad(e);
                i.setMad(q + 15);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l + 300);
                i.setMaxMp(b);
                i.setPdd(h + 100);
                i.setMdd(r + 60);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君阿尔泰手套一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君阿尔泰手套#k1个');
                cm.dispose();
                break;
            case 15:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1132174)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 25);
                i.setMad(q + 25);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 100);
                i.setMdd(r + 105);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君西亚戴斯腰带一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君西亚戴斯腰带#k1个');
                cm.dispose();
                break;
            case 16:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1132175)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 25);
                i.setMad(q + 25);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 105);
                i.setMdd(r + 105);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君赫尔梅斯腰带一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君赫尔梅斯腰带#k1个');
                cm.dispose();
                break;
            case 17:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1132176)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 25);
                i.setMad(q + 25);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 105);
                i.setMdd(r + 105);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君凯伦腰带一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君凯伦腰带#k1个');
                cm.dispose();
                break;
            case 18:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1132177)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 25);
                i.setMad(q + 25);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 105);
                i.setMdd(r + 105);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君利卡昂腰带一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君利卡昂腰带#k1个');
                cm.dispose();
                break;
            case 19:
                var t = Math.floor(Math.random() * 50) - 5;
                var j = Math.floor(Math.random() * 50) - 5;
                var g = Math.floor(Math.random() * 50) - 5;
                var n = Math.floor(Math.random() * 50) - 5;
                var q = Math.floor(Math.random() * 30) - 5;
                var e = Math.floor(Math.random() * 30) - 5;
                var s = Math.floor(Math.random() * 20) - 2;
                var d = Math.floor(Math.random() * 10) - 2;
                var c = Math.floor(Math.random() * 15) - 4;
                var a = Math.floor(Math.random() * 15) - 4;
                var l = Math.floor(Math.random() * 2200) - 200;
                var b = Math.floor(Math.random() * 1100) - 100;
                var h = Math.floor(Math.random() * 100) - 20;
                var r = Math.floor(Math.random() * 100) - 20;
                var k = Math.floor(Math.random() * 4);
                var m = cm.getItemInfo();
                var i = m.randomizeStats(m.getEquipById(1132178)).copy();
                i.setStr(t + 50);
                i.setDex(j + 50);
                i.setInt(g + 50);
                i.setLuk(n + 50);
                i.setPad(e + 25);
                i.setMad(q + 25);
                i.setBdr(s);
                i.setImdr(d);
                i.setDamR(c);
                i.setStatR(a);
                i.setMaxHp(l);
                i.setMaxMp(b);
                i.setPdd(h + 105);
                i.setMdd(r + 105);
                i.setUpgradeAvailable(k + 2);
                cm.addFromDrop(cm.getClient(), i, false);
                cm.worldMessage('公告事项 : 恭喜玩家 ' + cm.getPlayer().getName() + ' 从暴君防具交换券中获得了暴君阿尔泰腰带一个');
                cm.gainItem(2432069, -1);
                cm.sendOk('恭喜您，获得了#r暴君阿尔泰腰带#k1个');
                cm.dispose();
                break;
            }
        }
    }
}